name: cs442_mp2
description: "CS 442 MP2: Profile page"

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true  # Ensure this is only declared once
  assets:
    - assets/images/iit.jpeg       # IIT logo
    - assets/images/th.jpeg        # GTU logo
    - assets/images/zeel.jpeg      # Profile picture
    - assets/images/netflix.jpeg  # Netflix project logo
    - assets/images/crypto.jpeg   # Cryptocurrency project logo
    - assets/images/wishbox.jpeg  # Wishbox project logo
